In [2]:
import numpy as np

In [3]:
data1 = [3.5, 5, 6, 2]
arr1 = np.array(data1)

In [ ]:
arr1

array([3.5, 5. , 6. , 2. ])

In [7]:
data2 = (2, 56, 1.6)
arr2 = np.array(data2)

In [9]:
arr2

array([ 2. , 56. ,  1.6])

Massiv o'lchovi

In [10]:
arr1.ndim #array1 ning o'lchami

1

In [11]:
arr2.ndim #arr2 ning o'lchami

1

Ko'p o'lchamli

In [12]:
data3 = [[1,2,3,4], [5,6,7,8]] #list ichida list (nested list)
arr3  =np.array(data3)

In [15]:
arr3.ndim

2

3 o'lchamli o'zim uchun

In [26]:
data_uch = [[[1,2,3], [4,5,6], [7,8,9]]]
arr_uch = np.array(data_uch)

In [27]:
arr_uch.ndim

3

```shape``` , ```size``` metodlari

In [ ]:
arr_uch.shape # qator va ustunlar soni (q, u) agar 3 o'chamli bo'lsa blok, qator, ustun(b,q,u)

(1, 3, 3)

In [29]:
arr_uch.size # size- elementlar soni

9

N-o'lchamli massiv yaratish boshqa usullari

In [ ]:
arr4 = np.zeros(shape=(2,4)) #barchasi nolga teng
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr5 = np.ones((2,4)) #barchasi 1 ga teng
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

```arange``` funksiyasi yordamida

In [34]:
arr6 = np.arange(4,20,2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
arr7 = np.arange(20) #noldan 20 gacha 1 qadam bilan
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])