In [1]:
import numpy as np

In [2]:
data = np.random.rand(4)
data

array([0.45817301, 0.17530234, 0.73072282, 0.88108276])

In [3]:
sorted_array = np.sort(data)
sorted_array

array([0.17530234, 0.45817301, 0.73072282, 0.88108276])

In [5]:
data.sort()
data

array([0.17530234, 0.45817301, 0.73072282, 0.88108276])

In [7]:
rev_arr = -np.sort(-data)
rev_arr

array([0.88108276, 0.73072282, 0.45817301, 0.17530234])

In [8]:
arr2d = np.random.randn(2,4)
arr2d

array([[ 1.42349812, -0.80085529, -0.1862582 ,  0.44305314],
       [ 0.3935078 ,  0.00534931, -0.31397585,  0.16696637]])

In [9]:
#axis=0 --->Qator 
row_srt = np.sort(arr2d, axis = 0)
row_srt

array([[ 0.3935078 , -0.80085529, -0.31397585,  0.16696637],
       [ 1.42349812,  0.00534931, -0.1862582 ,  0.44305314]])

In [10]:
#axis=1 --->Ustun
col_srt = np.sort(arr2d, axis=1)
col_srt

array([[-0.80085529, -0.1862582 ,  0.44305314,  1.42349812],
       [-0.31397585,  0.00534931,  0.16696637,  0.3935078 ]])