In [3]:
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.save("data", arr)

In [6]:
arr2 = np.load("data.npy")
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.savez("arrays", a=arr, b=arr1)
arrays = np.load("arrays.npz")
arrays["a"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.savez_compressed("array_compress",a=arr, b=arr1)