In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y = np.array([[5., 5., 5.], [4., 4., 4.]])
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [4]:

x+y

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [5]:
y-x

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [6]:
x*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

### Matritsalarni ko'paytirish


In [7]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [9]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [10]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [11]:
y.dot(x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [12]:
np.dot(y,x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

### lineaer algebra

In [13]:
from numpy.linalg import inv