In [1]:
import numpy as np

In [2]:
# JAVOBNI SHU YERGA YOZING
def nd_array():
  """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi),
  qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
  return np.arange(0,9).reshape(3,3)
nd_array()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# JAVOBNI SHU YERGA YOZING
def sliced_array_2d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan
     qismini kesib olish funksiyasi """
    array = nd_array()
    return array[2,:2] # yuqoridagi funksiya yordamida array yaratib olish
sliced_array_2d()

array([6, 7])

In [5]:
def sliced_array_3d():
    """3-o'lchamli massivni yuqoridagi listdan yaratish,
    hamda 12, 13, 15, va 16 elementlarini kesib olish funksiyasi"""
    arr= np.arange(0,27).reshape(3,3,3)
    return arr[1][1:,:2]
sliced_array_3d()

array([[12, 13],
       [15, 16]])

In [6]:
# JAVOBNI SHU YERGA YOZING
def boolean_slicing():
    """Boolean indekslash yordamida ma'lumotlarni kesib olish """
    names = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
    info = np.array( [
    [5, 6, 1, 1],
   [9, 1, 1, 1],
   [7, 7, 4, 2],
   [1, 5, 1, 9],
   [9, 9, 4, 5],
   [7, 5, 9, 6],
   [5, 3, 7, 4]])
    
    mask = (names == "Javohir") | (names == "Elyor")
    return info[mask]
boolean_slicing()

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])