In [2]:
import numpy as np

In [3]:
arr1 = np.arange(10,100,10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
sliced_arr = arr1[3:6]
sliced_arr

array([40, 50, 60])

In [5]:
sliced_arr_copy = sliced_arr[:].copy()
sliced_arr_copy[:] = 1
print(sliced_arr_copy)
print(sliced_arr)

[1 1 1]
[40 50 60]


2-o'lchamli massiv


In [7]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2d[1,1]

np.int64(5)

In [11]:
arr2d[2,1:]

array([8, 9])

3 o'lchamli massivlar

In [12]:
arr3d = np.array([
    [[ 0,  1,  2],
     [ 3,  4,  5],
     [ 6,  7,  8]],

    [[ 9, 10, 11],
     [12, 13, 14],
     [15, 16, 17]],

    [[18, 19, 20],
     [21, 22, 23],
     [24, 25, 26]]
])

arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
arr3d[0][1,0]

np.int64(3)

In [ ]:
arr3d[0,1,3]  #demak bu xato ekan

IndexError: index 3 is out of bounds for axis 2 with size 3

In [15]:
arr3d[2][2,1:]

array([25, 26])