In [1]:
import numpy as np

In [4]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [3]:
data = np.random.randn(7,4)
data

array([[ 1.94034768e-01, -1.84482252e+00, -9.90438367e-02,
        -1.20043121e+00],
       [ 4.85660079e-01,  1.69681696e+00,  1.86177001e-01,
        -1.27395104e+00],
       [-1.13775688e+00,  8.84491096e-01,  3.06008214e-01,
        -9.11137506e-01],
       [ 1.37480804e+00,  6.85227149e-04, -7.22889106e-01,
        -5.26969343e-01],
       [-1.05575582e-01,  5.89407957e-01, -1.65392363e+00,
         5.41652382e-02],
       [-4.57103162e-01, -9.56005210e-01,  1.37889410e+00,
        -3.24826001e-01],
       [-6.23435436e-01,  6.14824841e-01, -1.21931674e+00,
         1.54462940e+00]])

In [7]:
names == "Hasan"

array([ True, False, False, False,  True, False, False])

In [ ]:
data[names == "Hasan"] #data ning ichidan Hasan ga tegishli barcha ma'lumotlarni olarkan

array([[ 0.19403477, -1.84482252, -0.09904384, -1.20043121],
       [-0.10557558,  0.58940796, -1.65392363,  0.05416524]])

In [22]:
data[names == "Hasan",  3] #qaysidir joyini kesib olish

array([-1.20043121,  0.05416524])

In [23]:
data[names == "Hasan",  3:] #qaysidir joyini kesib olish

array([[-1.20043121],
       [ 0.05416524]])

In [ ]:
res1 = data[names == "Hasan", 3]
res2 = data[names == "Hasan", 3:]

print(res1.ndim)
print(res2.ndim) 

1
2


In [25]:
data[~(names == "Hasan")]

array([[ 4.85660079e-01,  1.69681696e+00,  1.86177001e-01,
        -1.27395104e+00],
       [-1.13775688e+00,  8.84491096e-01,  3.06008214e-01,
        -9.11137506e-01],
       [ 1.37480804e+00,  6.85227149e-04, -7.22889106e-01,
        -5.26969343e-01],
       [-4.57103162e-01, -9.56005210e-01,  1.37889410e+00,
        -3.24826001e-01],
       [-6.23435436e-01,  6.14824841e-01, -1.21931674e+00,
         1.54462940e+00]])

In [28]:
mask = (names == "Hasan") | (names == "Husan")
mask

array([ True,  True, False, False,  True, False, False])

In [29]:
data[mask]

array([[ 0.19403477, -1.84482252, -0.09904384, -1.20043121],
       [ 0.48566008,  1.69681696,  0.186177  , -1.27395104],
       [-0.10557558,  0.58940796, -1.65392363,  0.05416524]])

In [30]:
zero_mask = data < 0
zero_mask

array([[False,  True,  True,  True],
       [False, False, False,  True],
       [ True, False, False,  True],
       [False, False,  True,  True],
       [ True, False,  True, False],
       [ True,  True, False,  True],
       [ True, False,  True, False]])

In [32]:
data[zero_mask] = 0
data

array([[1.94034768e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.85660079e-01, 1.69681696e+00, 1.86177001e-01, 0.00000000e+00],
       [0.00000000e+00, 8.84491096e-01, 3.06008214e-01, 0.00000000e+00],
       [1.37480804e+00, 6.85227149e-04, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.89407957e-01, 0.00000000e+00, 5.41652382e-02],
       [0.00000000e+00, 0.00000000e+00, 1.37889410e+00, 0.00000000e+00],
       [0.00000000e+00, 6.14824841e-01, 0.00000000e+00, 1.54462940e+00]])