In [1]:
import numpy as np


In [3]:
A = np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

Transpose

In [ ]:
A.T # A massivning Transpose ko'rinishi

array([[0, 2, 4],
       [1, 3, 5]])

Swapaxes

In [5]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.swapaxes(1,0)

array([[0, 2, 4],
       [1, 3, 5]])

dot()

In [7]:
np.dot(A, A.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])