In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.exp(arr) # e ning barcha darajalari ekan

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.log(arr[1:]) # natural logarifmni hisoblaydi e asosga ko'ra logarifm

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [10]:
arr1 = np.random.randn(6)
arr1

array([ 0.18172415,  0.27882102, -0.29384907, -1.32333977,  0.67580339,
       -0.60109754])

In [ ]:
qoldiq, butun = np.modf(arr1) # qoldiq va butun qismlarini qaytaradi
print(qoldiq, butun)

[ 0.18172415  0.27882102 -0.29384907 -0.32333977  0.67580339 -0.60109754] [ 0.  0. -0. -1.  0. -0.]


In [12]:
np.sign(arr1) # manfiy bo'lsa -1 musbat bo'lsa 1 qaytaradi

array([ 1.,  1., -1., -1.,  1., -1.])

In [13]:
arr1

array([ 0.18172415,  0.27882102, -0.29384907, -1.32333977,  0.67580339,
       -0.60109754])

In [14]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [19]:
arr1[0] = np.nan

In [20]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

# Binary Funktions

In [21]:
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [22]:
print(arr2)
print(arr3)

[-0.06648142 -0.97200958 -0.07507513  1.77958678  1.01698528 -1.79731132]
[-0.2536028   1.9613402  -0.71666591 -0.1277466  -0.88703977  0.77498303]


In [23]:
np.add(arr2,arr3)

array([-0.32008421,  0.98933062, -0.79174104,  1.65184018,  0.12994551,
       -1.02232829])

In [24]:
arr2 + arr3

array([-0.32008421,  0.98933062, -0.79174104,  1.65184018,  0.12994551,
       -1.02232829])

In [ ]:
np.multiply(arr2,arr3) # ko'paytirish

array([ 0.01685987, -1.90644147,  0.05380379, -0.22733617, -0.90210638,
       -1.39288577])

In [ ]:
np.maximum(arr2, arr3) # harbiridan kattasini yozib boradi

array([-0.06648142,  1.9613402 , -0.07507513,  1.77958678,  1.01698528,
        0.77498303])