In [2]:
import numpy as np

In [3]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

# Shart
cond = np.array([True, False, True, True, False])

# where
# cond==True bo'lsa xarr elementini oladi, cond==False bo'lsa yarr elementini oladi
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [6]:
arr = np.random.randn(4,4)
arr

array([[-0.33150206, -1.79490089, -1.87718224, -0.4145235 ],
       [-1.18116463, -0.2076661 ,  0.43201393, -0.52840269],
       [-2.47585604, -1.17111847, -0.61531635, -0.44388692],
       [-0.2515191 ,  2.23296016,  0.15372381,  1.27819485]])

In [8]:
result2 = np.where(arr <0, -2, -1)
result2

array([[-2, -2, -2, -2],
       [-2, -2, -1, -2],
       [-2, -2, -2, -2],
       [-2, -1, -1, -1]])