In [2]:
import numpy as np

In [3]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

In [5]:
print(arr1)
print(arr2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [4]:
#ko'paytirish
arr1 * arr2

array([[ 0,  7, 16],
       [27, 40, 55]])

In [7]:
#bo'lish
arr2/arr1

/tmp/ipykernel_5364/1570662862.py:2: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [8]:
#qo'shish
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [10]:
# ayirish
arr2 - arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [12]:
#kvadratga oshirish (square)
arr1 **2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [13]:
#kvadrat ildiz (sqrt)
arr2 ** 0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])