In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,4)
arr

array([[-0.07361053,  0.05681341, -0.27108771,  0.20048618],
       [-0.04622057, -0.15436521,  0.73899875,  0.38361826],
       [-0.77833493, -0.92834167,  0.08697082, -1.56018451],
       [-0.78640987,  0.54795785, -0.90854982,  0.12097374],
       [ 0.36823563, -0.01204488, -1.06753004,  0.11257121]])

### **Sum yozishni ikki xil usuli**

In [3]:
arr.sum()

np.float64(-3.9700538973502395)

In [4]:
np.sum(arr)

np.float64(-3.9700538973502395)

In [7]:
arr.sum(axis=1) #qator bo'yicha

array([-0.08739865,  0.92203123, -3.17989029, -1.0260281 , -0.59876808])

In [8]:
arr.sum(axis=0) #ustun bo'yicha

array([-1.31634027, -0.4899805 , -1.421198  , -0.74253513])

Mean metodi

In [11]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [12]:
mean = np.sum(data)/len(data)
mean

np.float64(2.0)

In [13]:
np.mean(data)

np.float64(2.0)

In [14]:
data.mean()

np.float64(2.0)

In [15]:
arr

array([[-0.07361053,  0.05681341, -0.27108771,  0.20048618],
       [-0.04622057, -0.15436521,  0.73899875,  0.38361826],
       [-0.77833493, -0.92834167,  0.08697082, -1.56018451],
       [-0.78640987,  0.54795785, -0.90854982,  0.12097374],
       [ 0.36823563, -0.01204488, -1.06753004,  0.11257121]])

In [16]:
arr.mean()

np.float64(-0.198502694867512)

In [17]:
np.mean(arr)

np.float64(-0.198502694867512)

In [ ]:
np.mean(arr, axis=1) #qator bo'yicha mean hisoblaydi

array([-0.02184966,  0.23050781, -0.79497257, -0.25650703, -0.14969202])

In [19]:
arr.mean(axis=0) #ustun bo'yicha mean hisoblaydi

array([-0.26326805, -0.0979961 , -0.2842396 , -0.14850703])

### CumSum

In [20]:
data

array([0, 1, 2, 3, 4])

In [21]:
data.cumsum()

array([ 0,  1,  3,  6, 10])