![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum

#8.26. NumPy kutubxonasi boʻyicha amaliy vazifa

Topshiriqni aynan qanday funksiyalar yordamida bajarish mumkinligi `💡Ishora` koʻrinishida berilgan.

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va uni chop eting.

Versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [4]:
import numpy as np
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 2. Raqamli qiymatlar roʻyxatini bir oʻlchovli NumPy massiviga aylantiring.

`💡Ishora` numpy.array

In [17]:
my_list = list([2,5,7])
arr = np.array(my_list)
arr

array([2, 5, 7])

#### 3. Qiymatlari noldan iborat boʻlgan toʻqqiz elementdan iborat massiv yarating.


---




`💡Ishora` np.zeros

In [18]:
arr1 = np.zeros(9)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [10]:

number = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')
full_memory = number.size * number.itemsize
print(full_memory)

80


#### 5. NumPy kutubxonasidagi `add` funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Shunday vekor yaratingki u oʻn ikki oʻlchamda va qiymatlari noldan iborat boʻlsin, lekin vektorning oltinchi qiymati 1 ga teng boʻlsin.



`💡Ishora` array[12]

In [19]:
arr2 = np.zeros(12).reshape(12,1)
arr2[5] =1
arr2

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

#### 7. Qiymatlari 20 dan 59 gacha boʻlgan vektor yarating.



`💡Ishora` arange

In [20]:
arr3 = np.arange(20,60) # 59 ham kiradi deb o'yladim, agar 59 kirmasin desangiz, shunchaki 60 ni o'rniga 59 yozish kerak
arr3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari oʻzgartiring, (birinchi element oxirgisi boʻlsin)



`💡Ishora` array[::-1]

In [27]:
arr4 = np.arange(1,15)
print(arr4)
arr4_reversed = arr4[::-1]
print(arr4_reversed)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1]


#### 9. 12 dan 20 gacha boʻlgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [29]:
arr5 = np.arange(12,21).reshape(3,3)
arr5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng boʻlmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [32]:
arr6 = np.array([3, 7, 0, 0, 9, 0])
index_nonzero = np.nonzero(arr6)
index_nonzero

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 oʻlchovidagi massiv yarating.


`💡Ishora` np.random.random

In [34]:
arr7 = np.random.random((2,2,2))
arr7

array([[[0.5141387 , 0.70950247],
        [0.36921357, 0.25429658]],

       [[0.56536914, 0.58209404],
        [0.19531666, 0.69478182]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 oʻlchamidagi massiv yarating. Soʻng uning eng katta va eng kichik qiymatlarini toping.


`💡Ishora` min, max

In [38]:
arr8 = np.random.random((9,9))
print(arr8)
print(f"min: {np.min(arr8)}")
print(f"max: {np.max(arr8)}")

[[0.32879821 0.44315229 0.87075142 0.28231494 0.43640486 0.90817974
  0.82643253 0.06625978 0.16331167]
 [0.78206873 0.75887783 0.50987784 0.63855129 0.48432633 0.19737116
  0.67574854 0.79506584 0.89000057]
 [0.07581756 0.75371269 0.54167438 0.55472523 0.87579328 0.1523933
  0.82215629 0.36592085 0.66352866]
 [0.51798    0.28554773 0.38584039 0.59685114 0.55398942 0.64976128
  0.49559822 0.56193919 0.74800833]
 [0.10207357 0.87404446 0.89645736 0.57667814 0.35419409 0.94471625
  0.97397002 0.20473863 0.73789482]
 [0.3147982  0.34409532 0.00763252 0.89125281 0.39167588 0.25059004
  0.02264177 0.55364137 0.22333768]
 [0.00998945 0.76039812 0.25249807 0.19080176 0.62669504 0.66928544
  0.77896493 0.855654   0.12599095]
 [0.30609379 0.08009209 0.18877986 0.14560062 0.81961853 0.99012404
  0.51995849 0.68489533 0.99831955]
 [0.08632122 0.7048537  0.06581747 0.90838911 0.5556761  0.54149853
  0.24073077 0.42372087 0.04028151]]
min: 0.007632515558948727
max: 0.9983195486987726


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
NaN
False
False
NaN
True
False


#### 14. Oʻlchamlari 6x3 va 3x4 boʻlgan martitsa yarating, soʻng ularning  koʻpaytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [43]:
arr9 = np.random.rand(18).reshape(6,3)
arr10 = np.random.rand(12).reshape(3,4)
print(np.dot(arr9,arr10))

[[0.82726882 1.85854941 1.03099392 1.73274477]
 [0.38249169 1.15784027 0.56192666 1.06453413]
 [0.7514508  1.92576937 1.01777913 1.69185962]
 [0.49959414 1.21431767 0.63919829 1.19349554]
 [0.91260998 1.52154224 1.0025346  1.33482592]
 [1.04425512 1.24908434 1.00019626 1.13757684]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [44]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [45]:
a = np.array([1, 2])
b = np.array([4,5])
print(a>b)
print(a >= b)
print(a <b)
print(a <=b)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [46]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_657/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_657/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_657/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping.


`💡Ishora` np.intersect1d

In [48]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

umumiy = np.intersect1d(a, b)

print("Umumiy qiymatlar:", umumiy)

Umumiy qiymatlar: [3 4 5]


#### 19. Tasodifiy sonlardan iborat boʻlgan massiv yarating, soʻng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` % (Sonning kasr qismi - qoldiq), np.floor, astype, np.trunc

In [50]:
massiv = np.random.randn(10)
massiv

array([-0.73440675,  0.74857874,  0.56029128,  0.40430383,  1.15564332,
       -0.26902069, -0.55866592,  1.33361358, -0.1066282 , -0.16221612])

In [51]:
#avval musbat sonlarni ajratib olay
musbat = massiv[massiv>0]
musbat

array([0.74857874, 0.56029128, 0.40430383, 1.15564332, 1.33361358])

In [53]:
# 1-usul
res1 = musbat - (musbat % 1)
res1

array([0., 0., 0., 1., 1.])

In [54]:
#2-usul
res2 = np.floor(musbat)
res2

array([0., 0., 0., 1., 1.])

In [56]:
#3-usul
res3 = musbat.astype(int)
res3

array([0, 0, 0, 1, 1])

In [58]:
#4-usul
res4 = np.trunc(musbat)
res4

array([0., 0., 0., 1., 1.])

#### 20. Oʻlchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha boʻlsin.



`💡Ishora` np.arange

In [59]:
Z = np.tile(np.arange(3), (3, 1))
Z

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. Oʻchamlari 10 boʻlgan tasodifiy vektor yarating va uni oʻsish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [61]:
massiv1 = np.random.rand(10)
np.sort(massiv1)

array([0.00593165, 0.18020101, 0.18815925, 0.20612404, 0.29258894,
       0.50166072, 0.659436  , 0.66384878, 0.78801865, 0.96257335])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [66]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
is_teng = np.array_equal(A, B)
print(is_teng)

False


#### 23. 5 dan 15 gacha bo'lgan sonlardan iborat massiv yarating. Massivdagi 10 dan katta elementlarni ajratib oling va ularning yig‘indisini hisoblang.


`💡Ishora` sum()

In [70]:
massiv4 = np.arange(5,16)
sum4 = np.sum(massiv4[massiv4>10])
sum4

np.int64(65)

#### 24. Tasodifiy sonlardan iborat boʻlgan oʻlchami 5 ga teng vektor yarating, soʻng uning eng katta qiymatini 0 ga oʻzgartiring.


`💡Ishora` argmax

In [72]:
massiv5 = np.random.randint(1,50, size=5)
print(massiv5)
massiv5[np.argmax(massiv5)] = 0
print(massiv5)

[48 29  8 49 22]
[48 29  8  0 22]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [73]:
bugun = np.datetime64('today', 'D')
kecha = bugun - np.timedelta64(1, 'D')
ertaga = bugun + np.timedelta64(1, 'D')

print(f"Kecha: {kecha}")
print(f"Bugun: {bugun}")
print(f"Ertaga: {ertaga}")

Kecha: 2026-03-17
Bugun: 2026-03-18
Ertaga: 2026-03-19


#### 26. 2016 yil yanvar oyiga toʻgʻri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [75]:
yanvar_sanalari = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
print(yanvar_sanalari)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 2.6, 7.9, 9.8, 4.2 elementlardan tashkil topgan arr yarating va uni arr1 deb nomlang. Keyin massivdagi har bir sonning butun qismini oling va yangi massiv - arr2 ni hosil qiling.


`💡Ishora` astype(int)

In [78]:
arr1 = np.array([2.6,7.9,9.8,4.2])
arr2 = arr1.astype(int)
arr2

array([2, 7, 9, 4])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yigʻindisini `np.sum` funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [79]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
yigindi = np.add.reduce(a)
print(yigindi)

55


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [81]:
a = np.array([1, 2, 3, 4, 5])
z = np.zeros(17)
z[::4] = a

print(z.astype(int))

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi `a` massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda `b` massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

`💡Ishora` stride_tricks.as_strided

In [83]:
# BU MASALANI ai DAN SO'RADIM, CHUNKI YAXSHI TUSHUNMADIM


import numpy as np
from numpy.lib import stride_tricks

# 1. Berilgan massiv
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

# 2. Parametrlarni aniqlaymiz
oyna_uzunligi = 4
qatorlar_soni = len(a) - oyna_uzunligi + 1

# 3. as_strided yordamida b massivini yaratamiz
b = stride_tricks.as_strided(
    a,
    shape=(qatorlar_soni, oyna_uzunligi),
    strides=(a.strides[0], a.strides[0])
)

print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga oʻxshash qiymatlar kiriting. Soʻng, oʻxshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [86]:
a = np.array([1, 3, 2, 8, 3, 5, 3, 2, 1, 9])
sanoq = np.bincount(a)
oxshash_qiymatlar = np.where(sanoq > 1)[0]

print(f"Asl massiv: {a}")
print(f"Takrorlangan (o'xshash) qiymatlar: {oxshash_qiymatlar}")

Asl massiv: [1 3 2 8 3 5 3 2 1 9]
Takrorlangan (o'xshash) qiymatlar: [1 2 3]


#### BONUS topshiriq

`💡Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.`

### Berilgan tasodifiy $5 \times 5$ matritsaning har bir qatoridagi o'rtacha qiymatni (mean) o'sha qatorning har bir elementidan ayirib tashlang.

In [88]:
X = np.random.rand(5, 5)
qator_ortachasi = X.mean(axis=1, keepdims=True)

Y = X - qator_ortachasi

print("Asl matritsaning birinchi qatori:\n", X[0])
print("\nO'rtacha qiymat ayirilgandan keyin:\n", Y[0])

Asl matritsaning birinchi qatori:
 [0.4510408  0.14995558 0.98014523 0.0726514  0.67248719]

O'rtacha qiymat ayirilgandan keyin:
 [-0.01421524 -0.31530046  0.51488919 -0.39260464  0.20723115]
